---
apiVersion: v1
kind: Service                    # Type of kubernetes resource
metadata:
  name: golang-kubernetes-app-service   # Name of the resource
spec:
  type: NodePort                 # A port is opened on each node in your cluster via Kube proxy.
  ports:                         # Take incoming HTTP requests on port 9090 and forward them to the targetPort of 8080
    - name: http
      port: 9090
      targetPort: 8080
  selector:
    app: golang-kubernetes-app         # Map any pod with label `app=go-hello-world` to this service
